--- 
- name: Check if remote host port
  wait_for: host={{ item.name }} port={{ item.port }} timeout=1
  ignore_errors: True
  with_items: "{{ servers }}"
  register: result{{ item.name }}{{ item.port }}
  #shell: printf "\n,{{ item.name }} port {{ item.port }} is {% if result.failed %}closed{% else %}open{% endif %}"  >> /tmp/{{ ansible_hostname }}_output.csv
  #args:
  #  executable: /bin/bash
  #when: ansible_hostname != item.name
