--- 
- name: Check if remote host port
  wait_for: host={{ item.name }} port={{ item.port }} timeout=1
  ignore_errors: True
  register: result
  #when: ansible_hostname != {{ item.name }}
  with_items: "{{ servers }}"

#- name: show
#  debug: msg={{result}}
  
  
- name: Save remote host port   
  shell: printf "\n,{{ item.name }} port {{ item.port }} is {% if result.failed %}closed{% else %}open{% endif %}"  >> /tmp/{{ ansible_hostname }}_output.csv
  args:
    executable: /bin/bash
  with_items: "{{ servers }}"
  #when: ansible_hostname != result.host
