---

- name: Check if remote {{ remote1 }} host port {{ port1 }}
  wait_for: host={{ remote1 }} port={{ port1 }} timeout=1
  ignore_errors: True
  register: result
  
#- debug: 
#    msg: "port failed: {{ result.failed }}"
  
- name: Save result in CSV
  shell: printf '\n,{{ remote1 }} port is {{ result.failed }}'  >> /tmp/x_output.csv
  args:
    executable: /bin/bash
