--- 
- name: Check if remote port
  block:
     - wait_for: host={{ item.name }} port={{ item.port }} timeout=1
     - shell: printf "\n,{{ item.host }} port {{ item.port }} is {% if item.failed %}closed{% else %}open{% endif %}"  >> /tmp/{{ ansible_hostname }}_output.csv
       args:
         executable: /bin/bash      
  #with_items: "{{ servers }}"
  ignore_errors: True
       #register: result
  
#- debug: var=result

#- name: show
#  debug: msg={{result}}
#- name: Transfer var=result
#  debug: msg={{item}}
#  with_items: "{{ result.results }}"
  
#- name: Save remote port   
#  shell: printf "\n,{{ item.host }} port {{ item.port }} is {% if item.failed %}closed{% else %}open{% endif %}"  >> /tmp/{{ ansible_hostname }}_output.csv
#  args:
#    executable: /bin/bash
#  with_items: "{{ result.results }}"
  
