--- 
- name: Check if remote port
  wait_for: host={{ item.name }} port={{ item.port }} timeout=1
  ignore_errors: True
  register: result
  #when: "{{ item.name }}" != ansible_hostname
  with_items: "{{ servers }}"

#- name: show
#  debug: msg={{result}}
- name: Transfer var=result
  debug: msg={{result.host}}
  
#- name: Save remote port   
#  shell: printf "\n,{{ item.host }} port {{ item.port }} is {% if item.failed %}closed{% else %}open{% endif %}"  >> /tmp/{{ ansible_hostname }}_output.csv
#  args:
#    executable: /bin/bash
#  with_items: "{{ result.results }}"
  
