--- 
- name: Check if remote host port
  wait_for: host={{ item.name }} port={{ item.port }} timeout=1
  ignore_errors: True
  register: result{{ item.name }}{{ item.port }}
  #when: ansible_hostname != {{ item.name }}
  with_items: "{{ servers }}"

- name: show
  debug: msg=result{{ item.name }}{{ item.port }}
  
  
#- name: Save remote host port   
#  shell: printf "\n,{{ item.name }} port {{ item.port }} is {% if result{{ item.name }}{{ item.port }}.failed %}closed{% else %}open{% endif %}"  >> /tmp/{{ ansible_hostname }}_output.csv
#  args:
#    executable: /bin/bash
#  #when: ansible_hostname != item.name
#  with_items: "{{ servers }}"
