--- 
- name: Check if remote port
  wait_for: host={{ item.name }} port={{ item.port }} timeout=1
  ignore_errors: True
  register: out
  with_items: "{{ servers }}"
    
- debug: var=out
#- debug: msg={{ result }}

#- name: show
#  debug: msg={{result}}
#- name: Transfer var=result
#  debug: msg={{item}}
#  with_items: "{{ result.results }}"
  
- name: Save remote port   
#  shell: printf "\n,{{ item.host }} port {{ item.port }} is {% if item.failed %}closed{% else %}open{% endif %}"  >> /tmp/{{ ansible_hostname }}_output.csv
  shell: echo {{ item.name }} > /tmp/x_output.csv
  #shell: echo 1 > /tmp/x_output.csv
  args:
    executable: /bin/bash
  with_items: "{{ out.results }}"
  
