---

- name: Check if remote {{ remote1 }} host port {{ port1 }}
  wait_for: host={{ remote1 }} port={{ port1 }} timeout=1
  ignore_errors: True
  register: result
  
- name: Save result in CSV
  shell: printf '\n,test'  >> /tmp/{{ ansible_hostname }}_output.csv
  args:
    executable: /bin/bash
